stages:
  - build
  - code_analysis
  - mvn_install


before_script:
  - git reset --hard $CI_COMMIT_SHA
  - git clean -df
  - git stash
  - git pull origin $CI_COMMIT_SHA



#after_script:
#  - git reset --hard HEAD
#  - git clean -df
#  - git stash
#  - git pull origin $CI_COMMIT_REF_NAME
svarog-build:
  stage: build
  script:
    - mvn clean compile

svarog-json:
  stage: generate-json
  script:
    - cd $CI_PROJECT_DIR
    - mvn exec:java@json

svarog-unit-tests:
  stage: install-postgres-ut
  script:
    - cd .gitlab-ci
    - ansible -m ping gitlab-ci-runner -i hosts/gitlabci.yml
    - ./ansible-svarog.sh UT $CI_PROJECT_DIR POSTGRES
    - cd $CI_PROJECT_DIR
    - mvn exec:java@install-drop -P PostgreSQL
    - mvn test -P PostgreSQL
  
  stage: upgrade-postgres-ut
  script:
    - mvn exec:java@upgrade-force -P PostgreSQL
    - mvn test -P PostgreSQL
    
  stage: install-oracle-ut
  script:
    - cd .gitlab-ci
    - ansible -m ping gitlab-ci-runner -i hosts/gitlabci.yml
    - ./ansible-svarog.sh UT $CI_PROJECT_DIR ORACLE
    - cd $CI_PROJECT_DIR
    - mvn exec:java@install-drop-auto -P Oracle

  stage: upgrade-oracle-ut
  script:
    - mvn exec:java@upgrade-force-auto -P Oracle
    - mvn test -P Oracle
    
svarog-upgrade:
  stage: upgrade-postgres-pipeline
  script:
    - cd .gitlab-ci
    - ansible -m ping gitlab-ci-runner -i hosts/gitlabci.yml
    - ./ansible-svarog.sh $CI_COMMIT_REF_NAME $CI_PROJECT_DIR POSTGRES
    - cd $CI_PROJECT_DIR  
    - mvn exec:java@upgrade-force -P PostgreSQL
    - mvn test -P PostgreSQL
    
  stage: upgrade-oracle-pipeline
  script:
    - cd .gitlab-ci
    - ansible -m ping gitlab-ci-runner -i hosts/gitlabci.yml
    - ./ansible-svarog.sh $CI_COMMIT_REF_NAME $CI_PROJECT_DIR ORACLE
    - cd $CI_PROJECT_DIR  
    - mvn exec:java@upgrade-force -P Oracle
    - mvn test -P Oracle
    
    - cd $CI_PROJECT_DIR
    - cd target/surefire-reports
    - zip -r surefire-reports.zip *
  artifacts:
    name: "${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}_${CI_PIPELINE_ID}"
    when: always
    paths:
    - $CI_PROJECT_DIR/target/surefire-reports/surefire-reports.zip
    expire_in: 15 days
  environment:
    name: $CI_COMMIT_REF_NAME
  only:
    - master
    - staging
    - dev


svarog-sonarqube:
  stage: code_analysis
  script:
    - mvn sonar:sonar -Dsonar.analysis.mode=preview
    
svarog-install:
  stage: mvn_install
  script:  
    - pwd
    - mvn install -DskipTests
  only:
    - master
    - staging
    - dev    
