SELECT UPPER(COLUMN_NAME) FIELD_NAME,
       CASE 
          WHEN upper(DATA_TYPE)='CHARACTER VARYING' THEN 'NVARCHAR'
          WHEN upper(DATA_TYPE)='NUMERIC' THEN 'NUMERIC'
          WHEN upper(DATA_TYPE)='BOOLEAN' THEN 'BOOLEAN'
          WHEN upper(DATA_TYPE)='TIMESTAMP' THEN 'TIMESTAMP'
          WHEN upper(DATA_TYPE)='DATE' THEN 'DATE'
          WHEN upper(DATA_TYPE) like 'TIMESTAMP%' THEN 'TIMESTAMP'
		  WHEN upper(DATA_TYPE) like 'TEXT' THEN 'TEXT'
		  WHEN UPPER(DATA_TYPE) LIKE upper('user-defined') AND upper(udt_name)='GEOMETRY' THEN 'GEOMETRY'
          ELSE 'UNKNOWN'
       END
          FIELD_TYPE,
CASE WHEN IS_NULLABLE='YES' THEN 'Y' ELSE 'N' END IS_NULL,

       CASE
          WHEN upper(DATA_TYPE) ='CHARACTER VARYING' THEN CHARACTER_MAXIMUM_LENGTH
          WHEN upper(DATA_TYPE) ='NUMERIC' THEN NUMERIC_PRECISION
          WHEN upper(DATA_TYPE) ='BOOLEAN' THEN 0
          WHEN upper(DATA_TYPE) LIKE 'TIMESTAMP%' THEN DATETIME_PRECISION
          
          ELSE 0
       END
          FIELD_SIZE,
          CASE WHEN upper(DATA_TYPE) = 'NUMERIC' THEN NUMERIC_SCALE ELSE NULL END
          FIELD_SCALE
FROM INFORMATION_SCHEMA.COLUMNS ISC
WHERE UPPER(TABLE_NAME)=UPPER('{TABLE_NAME}')
AND UPPER(TABLE_SCHEMA)=UPPER('{SCHEMA_NAME}')