---
- name: "Apply svarog.properties template for branch {{ env_name }}"
  template:
    src: svarog.properties.tpl
    dest: svarog.properties

- name: Register output for svarog.properties
  shell: svarog.properties
  register: cat_output

- name: Display output for svarog.properties
  debug:
    var: cat_output
