---
- name: "Apply svarog.properties ORACLE template for branch {{ env_name }}"
  template:
    src: "{{ base_dir }}/svarog.properties.tpl"
    dest: "{{ base_dir }}/svarog.properties"

- name: Register output for ORACLE svarog.properties
  shell: cat "{{ base_dir }}/svarog.properties"
  register: cat_output

- name: Display output for ORACLE svarog.properties
  debug:
    var: cat_output
