---
# replace variables
- name: Set ORACLE username and password
  set_fact:
    db_username: "{{ master_oracle_username }}"
    db_password: "{{ master_oracle_password }}"
  when: env_name == "master"

- name: Set ORACLE username and password
  set_fact:
    db_username: "{{ staging_oracle_username }}"
    db_password: "{{ staging_oracle_password }}"
  when: env_name == "staging"

- name: Set ORACLE username and password
  set_fact:
    db_username: "{{ dev_oracle_username }}"
    db_password: "{{ dev_oracle_password }}"
  when: env_name == "dev"

- name: Set ORACLE username and password
  set_fact:
    db_username: "{{ ut_oracle_username }}"
    db_password: "{{ ut_oracle_password }}"
  when: env_name == "ut"

- name: Set ORACLE generic variables
  set_fact:
    db_driver_name: "{{ oracle_driver_name }}"
    db_connstring: "{{ oracle_connstring }}"
    db_schema: "{{ oracle_schema }}"
    db_type: "{{ oracle_db_type }}"
    db_conn_type: JDBC
    db_handler: "{{ oracle_db_handler }}"
