---
# replace variables
- name: Set postgres schema
  set_fact:
    db_schema: "{{ master_postgres_schema }}"
  when: env_name == "master"

- name: Set postgres schema
  set_fact:
    db_schema: "{{ staging_postgres_schema }}"
  when: env_name == "staging"

- name: Set postgres schema
  set_fact:
    db_schema: "{{ dev_postgres_schema }}"
  when: env_name == "dev"

- name: Set POSTGRES generic variables
  set_fact:
    db_username: "{{ postgres_username }}"
    db_password: "{{ postgres_password }}"
    db_driver_name: "{{ postgres_driver_name }}"
    db_connstring: "{{ postgres_connstring }}"
    db_type: "{{ postgres_db_type }}"
    db_conn_type: JDBC
